### ISSUE TITLE
Doesn't work on M1 - tested with 2.13.6

### ISSUE THREAD

**Issue by Bexin3** [FabricMC/fabric-language-scala#20]
This is all I get when it crashes:

_[23:38:53] [Render thread/WARN]: Failed retrieving info for group virtual memory
--
1099 | java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.mac.SystemB
1100 | at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:80) ~[oshi-core-5.8.5.jar:?]
1101 | at oshi.hardware.platform.mac.MacGlobalMemory.queryPhysMem(MacGlobalMemory.java:146) ~[oshi-core-5.8.5.jar:?]
1102 | at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-5.8.5.jar:?]
1103 | at oshi.hardware.platform.mac.MacGlobalMemory.getTotal(MacGlobalMemory.java:74) ~[oshi-core-5.8.5.jar:?]
1104 | at oshi.hardware.platform.mac.MacVirtualMemory.getVirtualMax(MacVirtualMemory.java:82) ~[oshi-core-5.8.5.jar:?]
1105 | at net.minecraft.util.SystemDetails.method_37152(SystemDetails.java:98) ~[client-intermediary.jar:?]
1106 | at net.minecraft.util.SystemDetails.addSection(SystemDetails.java:65) ~[client-intermediary.jar:?]
1107 | at net.minecraft.util.SystemDetails.addVirtualMemoryGroup(SystemDetails.java:98) ~[client-intermediary.jar:?]
1108 | at net.minecraft.util.SystemDetails.method_37139(SystemDetails.java:106) ~[client-intermediary.jar:?]
1109 | at net.minecraft.util.SystemDetails.tryAddGroup(SystemDetails.java:81) ~[client-intermediary.jar:?]
1110 | at net.minecraft.util.SystemDetails.addGlobalMemoryGroup(SystemDetails.java:106) ~[client-intermediary.jar:?]
1111 | at net.minecraft.util.SystemDetails.method_37133(SystemDetails.java:76) ~[client-intermediary.jar:?]
1112 | at net.minecraft.util.SystemDetails.tryAddGroup(SystemDetails.java:81) ~[client-intermediary.jar:?]
1113 | at net.minecraft.util.SystemDetails.addHardwareGroup(SystemDetails.java:76) ~[client-intermediary.jar:?]
1114 | at net.minecraft.util.SystemDetails.method_37143(SystemDetails.java:51) ~[client-intermediary.jar:?]
1115 | at net.minecraft.util.SystemDetails.tryAddGroup(SystemDetails.java:81) [client-intermediary.jar:?]
1116 | at net.minecraft.util.SystemDetails.<init>(SystemDetails.java:51) [client-intermediary.jar:?]
1117 | at net.minecraft.util.crash.CrashReport.<init>(CrashReport.java:32) [client-intermediary.jar:?]
1118 | at net.minecraft.util.crash.CrashReport.create(CrashReport.java:264) [client-intermediary.jar:?]
1119 | at net.minecraft.client.main.Main.main(Main.java:204) [client-intermediary.jar:?]
1120 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
1121 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
1122 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
1123 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
1124 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
1125 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
1126 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
1127 | at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
1128 | at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
1129 | at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
1130 | at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
1131 | at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]

[23:38:53] [Render thread/WARN]: Failed retrieving info for group virtual memory
[1099](https://mclo.gs/lbuvsJC#L1099)	java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.mac.SystemB
[1100](https://mclo.gs/lbuvsJC#L1100)		at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:80) ~[oshi-core-5.8.5.jar:?]
[1101](https://mclo.gs/lbuvsJC#L1101)		at oshi.hardware.platform.mac.MacGlobalMemory.queryPhysMem(MacGlobalMemory.java:146) ~[oshi-core-5.8.5.jar:?]
[1102](https://mclo.gs/lbuvsJC#L1102)		at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-5.8.5.jar:?]
[1103](https://mclo.gs/lbuvsJC#L1103)		at oshi.hardware.platform.mac.MacGlobalMemory.getTotal(MacGlobalMemory.java:74) ~[oshi-core-5.8.5.jar:?]
[1104](https://mclo.gs/lbuvsJC#L1104)		at oshi.hardware.platform.mac.MacVirtualMemory.getVirtualMax(MacVirtualMemory.java:82) ~[oshi-core-5.8.5.jar:?]
[1105](https://mclo.gs/lbuvsJC#L1105)		at net.minecraft.util.SystemDetails.method_37152(SystemDetails.java:98) ~[client-intermediary.jar:?]
[1106](https://mclo.gs/lbuvsJC#L1106)		at net.minecraft.util.SystemDetails.addSection(SystemDetails.java:65) ~[client-intermediary.jar:?]
[1107](https://mclo.gs/lbuvsJC#L1107)		at net.minecraft.util.SystemDetails.addVirtualMemoryGroup(SystemDetails.java:98) ~[client-intermediary.jar:?]
[1108](https://mclo.gs/lbuvsJC#L1108)		at net.minecraft.util.SystemDetails.method_37139(SystemDetails.java:106) ~[client-intermediary.jar:?]
[1109](https://mclo.gs/lbuvsJC#L1109)		at net.minecraft.util.SystemDetails.tryAddGroup(SystemDetails.java:81) ~[client-intermediary.jar:?]
[1110](https://mclo.gs/lbuvsJC#L1110)		at net.minecraft.util.SystemDetails.addGlobalMemoryGroup(SystemDetails.java:106) ~[client-intermediary.jar:?]
[1111](https://mclo.gs/lbuvsJC#L1111)		at net.minecraft.util.SystemDetails.method_37133(SystemDetails.java:76) ~[client-intermediary.jar:?]
[1112](https://mclo.gs/lbuvsJC#L1112)		at net.minecraft.util.SystemDetails.tryAddGroup(SystemDetails.java:81) ~[client-intermediary.jar:?]
[1113](https://mclo.gs/lbuvsJC#L1113)		at net.minecraft.util.SystemDetails.addHardwareGroup(SystemDetails.java:76) ~[client-intermediary.jar:?]
[1114](https://mclo.gs/lbuvsJC#L1114)		at net.minecraft.util.SystemDetails.method_37143(SystemDetails.java:51) ~[client-intermediary.jar:?]
[1115](https://mclo.gs/lbuvsJC#L1115)		at net.minecraft.util.SystemDetails.tryAddGroup(SystemDetails.java:81) [client-intermediary.jar:?]
[1116](https://mclo.gs/lbuvsJC#L1116)		at net.minecraft.util.SystemDetails.<init>(SystemDetails.java:51) [client-intermediary.jar:?]
[1117](https://mclo.gs/lbuvsJC#L1117)		at net.minecraft.util.crash.CrashReport.<init>(CrashReport.java:32) [client-intermediary.jar:?]
[1118](https://mclo.gs/lbuvsJC#L1118)		at net.minecraft.util.crash.CrashReport.create(CrashReport.java:264) [client-intermediary.jar:?]
[1119](https://mclo.gs/lbuvsJC#L1119)		at net.minecraft.client.main.Main.main(Main.java:204) [client-intermediary.jar:?]
[1120](https://mclo.gs/lbuvsJC#L1120)		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
[1121](https://mclo.gs/lbuvsJC#L1121)		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
[1122](https://mclo.gs/lbuvsJC#L1122)		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
[1123](https://mclo.gs/lbuvsJC#L1123)		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[1124](https://mclo.gs/lbuvsJC#L1124)		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[1125](https://mclo.gs/lbuvsJC#L1125)		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[1126](https://mclo.gs/lbuvsJC#L1126)		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[1127](https://mclo.gs/lbuvsJC#L1127)		at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
[1128](https://mclo.gs/lbuvsJC#L1128)		at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
[1129](https://mclo.gs/lbuvsJC#L1129)		at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
[1130](https://mclo.gs/lbuvsJC#L1130)		at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
[1131](https://mclo.gs/lbuvsJC#L1131)		at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]_

**Comment by Bexin3** [comment]
Same core issue as issue 17
